insert into creators (
  display_name,
  primary_niche,
  country,
  status,
  creator_type,
  phone,
  handle,
  tiktok_url,
  instagram_url,
  instagram_handle,
  tiktok_handle,
  followers,
  category,
  portfolio_url,
  age,
  gender,
  languages,
  accepts_gifted_collab,
  turnaround_time,
  has_equipment,
  has_editing_skills,
  can_voiceover,
  skills_rating,
  base_rate,
  profile_image,
  has_mock_video,
  notes
)
select
  'Salma Nour',
  'Beauty, Lifestyle',
  'Egypt',
  'vetted',
  'UGC',
  '+20 111 234 5678',
  '@salmanour',
  null,
  'https://instagram.com/salmanour',
  'salmanour',
  null,
  null,
  null,
  'https://portfolio.example.com/salma',
  24,
  'Female',
  'AR, EN',
  true,
  '5-7 days',
  true,
  true,
  true,
  4.6,
  350,
  null,
  true,
  'Strong UGC routines and skincare storytelling.'
where not exists (
  select 1 from creators where display_name = 'Salma Nour'
);

insert into creators (
  display_name,
  primary_niche,
  country,
  status,
  creator_type,
  phone,
  handle,
  tiktok_url,
  instagram_url,
  instagram_handle,
  tiktok_handle,
  followers,
  category,
  portfolio_url,
  age,
  gender,
  languages,
  accepts_gifted_collab,
  turnaround_time,
  has_equipment,
  has_editing_skills,
  can_voiceover,
  skills_rating,
  base_rate,
  profile_image,
  has_mock_video,
  notes
)
select
  'Omar Elshenawy',
  'Tech, Lifestyle',
  'UAE',
  'vetted',
  'Influencer',
  '+971 50 123 4567',
  '@omartech',
  'https://tiktok.com/@omartech',
  'https://instagram.com/omartech',
  'omartech',
  'omartech',
  220000,
  'Tech',
  null,
  28,
  'Male',
  'EN',
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  'High engagement on TikTok reviews.'
where not exists (
  select 1 from creators where display_name = 'Omar Elshenawy'
);

insert into creators (
  display_name,
  primary_niche,
  country,
  status,
  creator_type,
  phone,
  handle,
  tiktok_url,
  instagram_url,
  instagram_handle,
  tiktok_handle,
  followers,
  category,
  portfolio_url,
  age,
  gender,
  languages,
  accepts_gifted_collab,
  turnaround_time,
  has_equipment,
  has_editing_skills,
  can_voiceover,
  skills_rating,
  base_rate,
  profile_image,
  has_mock_video,
  notes
)
select
  'Lena Mansour',
  'Fashion, Lifestyle',
  'Egypt',
  'vetted',
  'UGC',
  '+20 122 987 6543',
  '@lenamansour',
  null,
  'https://instagram.com/lenamansour',
  'lenamansour',
  null,
  null,
  null,
  'https://portfolio.example.com/lena',
  23,
  'Female',
  'AR',
  true,
  '3-5 days',
  true,
  false,
  true,
  4.2,
  280,
  null,
  false,
  'Fashion UGC with strong conversion hooks.'
where not exists (
  select 1 from creators where display_name = 'Lena Mansour'
);

insert into creators (
  display_name,
  primary_niche,
  country,
  status,
  creator_type,
  phone,
  handle,
  tiktok_url,
  instagram_url,
  instagram_handle,
  tiktok_handle,
  followers,
  category,
  portfolio_url,
  age,
  gender,
  languages,
  accepts_gifted_collab,
  turnaround_time,
  has_equipment,
  has_editing_skills,
  can_voiceover,
  skills_rating,
  base_rate,
  profile_image,
  has_mock_video,
  notes
)
select
  'Nour Ali',
  'Lifestyle, Wellness',
  'UAE',
  'vetted',
  'Influencer',
  '+971 55 678 1234',
  '@nourali',
  'https://tiktok.com/@nourali',
  'https://instagram.com/nourali',
  'nourali',
  'nourali',
  145000,
  'Lifestyle',
  null,
  27,
  'Female',
  'EN, AR',
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  'Wellness influencer with strong brand fit.'
where not exists (
  select 1 from creators where display_name = 'Nour Ali'
);
