alter table creators
  add column creator_type text check (creator_type in ('UGC', 'Influencer', 'Hybrid')),
  add column phone text,
  add column handle text,
  add column tiktok_url text,
  add column instagram_url text,
  add column instagram_handle text,
  add column tiktok_handle text,
  add column followers integer,
  add column category text,
  add column portfolio_url text,
  add column age integer,
  add column gender text,
  add column languages text,
  add column accepts_gifted_collab boolean,
  add column turnaround_time text,
  add column has_equipment boolean,
  add column has_editing_skills boolean,
  add column can_voiceover boolean,
  add column skills_rating numeric(2, 1),
  add column base_rate numeric(12, 2),
  add column profile_image text,
  add column has_mock_video boolean,
  add column notes text;
